### ISSUE TITLE
Connecting models to frontend

### ISSUE THREAD

**Issue by ayubsoft254** [ayubsoft254/ttu_blog#4]
Connecting models to frontend

**Comment by DOOLB-lab** [comment]
uko online nikupigie ,,,nilimake some changes alafu nata nijue leo tunafanya

**Comment by ayubsoft254** [comment]
https://meet.google.com/kmq-tbjd-bmk

**Comment by ayubsoft254** [comment]
join tena stima ilikua imepotea

**Comment by ayubsoft254** [comment]
done
