### ISSUE TITLE
Model Fix

### ISSUE THREAD

**Issue by ayubsoft254** [ayubsoft254/ttu_blog#6]
Hi Makai

I've reviewed the pull request you submitted, and there are a few adjustments needed to align with our requirements. Please address the following points:

Navbar Link Issue: The link for stories on the navbar is missing. Please ensure the stories collection link is functional. Update the URL accordingly.

Story Detail Template: The story detail page currently uses multiple templates. We need to consolidate this into a single template. Use the story ID to call the relevant values instead of templates like open_relationships.html.

Styling: The templates should pull their styling from the CSS files. Please remove any Bootstrap styling and ensure that all styles are defined in the CSS files.

Model Images: The models were supposed to include images for each component. It appears that the images are missing. Please add the image fields to the models and ensure they are displayed correctly.

Could you please make these updates and push the changes? Let me know if you have any questions or need further clarification.

Thanks!

**Comment by itMakai** [comment]
should I create the views relevant to the model to handle the issue of multtamplates?

**Comment by ayubsoft254** [comment]
Done
